[workspace]
members = ["binary_reader", "classfile", "javap"]
resolver = "3"

[profile.dev]
opt-level = 0
debug-assertions = true
incremental = true

[profile.release]
opt-level = 3
debug-assertions = false
incremental = false
